# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import communication_pb2 as communication__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in communication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeCommunicationStub(object):
    """The service definition for Node-to-Node communication.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeAction = channel.unary_unary(
                '/communication.NodeCommunication/ProposeAction',
                request_serializer=communication__pb2.ActionRequest.SerializeToString,
                response_deserializer=communication__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/communication.NodeCommunication/Heartbeat',
                request_serializer=communication__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=communication__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetNodeStatus = channel.unary_unary(
                '/communication.NodeCommunication/GetNodeStatus',
                request_serializer=communication__pb2.NodeStatusRequest.SerializeToString,
                response_deserializer=communication__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/communication.NodeCommunication/RequestVote',
                request_serializer=communication__pb2.VoteRequest.SerializeToString,
                response_deserializer=communication__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/communication.NodeCommunication/AppendEntries',
                request_serializer=communication__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=communication__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)


class NodeCommunicationServicer(object):
    """The service definition for Node-to-Node communication.
    """

    def ProposeAction(self, request, context):
        """Propose an action to other nodes (part of Raft or direct communication)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat/Sync for maintaining active node list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStatus(self, request, context):
        """Status introspection — used by the dashboard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """── Raft Consensus RPCs ──

        Invoked by candidates to gather votes during leader election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Invoked by leader to replicate log entries and serve as heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeAction,
                    request_deserializer=communication__pb2.ActionRequest.FromString,
                    response_serializer=communication__pb2.ActionResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=communication__pb2.HeartbeatRequest.FromString,
                    response_serializer=communication__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStatus,
                    request_deserializer=communication__pb2.NodeStatusRequest.FromString,
                    response_serializer=communication__pb2.NodeStatusResponse.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=communication__pb2.VoteRequest.FromString,
                    response_serializer=communication__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=communication__pb2.AppendEntriesRequest.FromString,
                    response_serializer=communication__pb2.AppendEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'communication.NodeCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('communication.NodeCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeCommunication(object):
    """The service definition for Node-to-Node communication.
    """

    @staticmethod
    def ProposeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.NodeCommunication/ProposeAction',
            communication__pb2.ActionRequest.SerializeToString,
            communication__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.NodeCommunication/Heartbeat',
            communication__pb2.HeartbeatRequest.SerializeToString,
            communication__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.NodeCommunication/GetNodeStatus',
            communication__pb2.NodeStatusRequest.SerializeToString,
            communication__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.NodeCommunication/RequestVote',
            communication__pb2.VoteRequest.SerializeToString,
            communication__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.NodeCommunication/AppendEntries',
            communication__pb2.AppendEntriesRequest.SerializeToString,
            communication__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
